### PR TITLE
Show Calendarific Sensors in Home Assistant Calendar

### LINKED ISSUE #20: Feature request: Add sensor dates to the Home Assistant calendar
It would be nice to have them added to the HA calendar. Perhaps this project can help:

https://github.com/bruxy70/Garbage-Collection/blob/development/custom_components/garbage_collection/calendar.py

### PR DESCRIPTION
**Pull request by Snuffy2**
I believe I have added the Calendar platform into the Calendarific integration. I've done some testing and it is working for me, but others need need to test more for sure. 

Fixes: #20

### CODE REVIEW

**Comment by pinkywafer** [comment]
great.  I'll look this over and merge if all is well.  Thank you very much

**Comment by pinkywafer** [comment]
ok, having reviewed this, I'm not going to merge, as there is too much going on in this PR.
This should be at least 2 seperate PRs - 
The adding of the calendar should be in a PR
Any code styling / cleanup of the existing integration should be separate to the PR adding a new feature.  

I'm going to leave the PR open for the time being to see what you would like to do with it: 
split the additions into a PR on their own, 
create a separate styling pr if you wish

otherwise, I am happy to add the calendar enhancement using your calendar.py and the associated additions in const and sensor, and will credit you anyway.

Please let me know how you'd like to proceed.  If I do not hear from you, I shall do the latter and add the calendar etc and credit you.
Thanks

**Comment by Snuffy2** [comment]
Fair. I did these PRs months ago and was using a new IDE. I generally have auto-Black linting enabled and must have left it on for this as well. Let me see what I can do to remove the code formatting changes (in both PRs)

**Comment by Snuffy2** [comment]
Ok, it wasn't as difficult as I had imagined to revert the formatting changes. There are still a couple remaining but hopefully this is better now.

**Review by pinkywafer — APPROVED** [review]

**Comment by pinkywafer** [comment]
Thanks

**Pull request merged**
